**NUMPY TUTORIALS** - used for creating multi-dimensional array

**What is an Array?** - data structure of same data type, rest is similar to lists

In [48]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


**else we can use** conda install numpy

In [50]:
import numpy as np

In [12]:
my_lst = [1,2,3,4]

In [14]:
arr = np.array(my_lst)

In [18]:
type(arr)

numpy.ndarray

In [24]:
arr #1D array

array([1, 2, 3, 4])

In [22]:
arr.shape

(4,)

**Can we convert 1D array to 2D?**

Answer is yes

using arr.reshape()

In [34]:
#Multinested array

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,6,7]
my_lst3=[4,6,7,9,0]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [36]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 6, 7],
       [4, 6, 7, 9, 0]])

In [38]:
arr.shape

(3, 5)

In [40]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 6],
       [7, 4, 6],
       [7, 9, 0]])

**Check the closing braces to understand the array dimension**

**INDEXING**

In [52]:
#Accessing the array element

arr = np.array([1,2,3,4,5,5,4,3])

In [54]:
arr[2]

np.int64(3)

In [58]:

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,6,7]
my_lst3=[4,6,7,9,0]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [60]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 6, 7],
       [4, 6, 7, 9, 0]])

In [62]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [64]:
arr[1:,3:]

array([[6, 7],
       [9, 0]])

**IN-BUILT FUNCTIONS**

In [71]:
arr=np.arange(0,10) #has 3 parameters(start, stop, step)

In [73]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
#using the step parameter

arr=np.arange(0,10,2)

In [77]:
arr

array([0, 2, 4, 6, 8])

In [79]:
#Linspace - generates equally spaced points for the given/specified range

np.linspace(1,10,30) #It will generate 30 points(equally spaced between 0 and 10)

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [81]:
#Copy() and Broadcasting

arr



array([0, 2, 4, 6, 8])

In [83]:
arr[3:]=10

In [85]:
arr

array([ 0,  2,  4, 10, 10])

In [87]:
arr1=arr

In [89]:
arr1[2:]=20

In [91]:
arr1

array([ 0,  2, 20, 20, 20])

In [93]:
arr

array([ 0,  2, 20, 20, 20])

**Array is reference type: meaning these 2 arrays are sharing the same memory**

2 types: reference type and value type

**In-order to prevent this from happening, we have to use copy()**

In [100]:
arr

array([ 0,  2, 20, 20, 20])

In [102]:
arr1=arr.copy()

In [104]:
print(arr)

[ 0  2 20 20 20]


In [106]:
arr1[2:]=10

In [108]:
print(arr1)

[ 0  2 10 10 10]


**#While copy function is used, another memory space is created and not replacing the content from arr as it was done earlier.**

**Some conditions which are very useful in Exploratory Data Analysis**

In [114]:
val =2

In [116]:
arr<10

array([ True,  True, False, False, False])

In [118]:
arr[arr<10]

array([0, 2])

**Some more In-Built FUnctions**

In [121]:
np.ones(4) #all the elements are basically replaced by 1

#Syntax: np.ones(shape, dtype) - dtype is float by default

array([1., 1., 1., 1.])

In [123]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [125]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**Random Distribution**

In [132]:
np.random.rand(3,4) #Generates random values for the given shape

array([[0.8545547 , 0.91889326, 0.1574508 , 0.84110528],
       [0.49971274, 0.25213175, 0.97622278, 0.36985683],
       [0.56248483, 0.31580039, 0.90988657, 0.13269293]])

In [134]:
np.random.randn(4,3) #Takes values based on standard normal distribution

array([[-1.68338306, -0.54164668,  1.08220596],
       [-1.20277443, -1.44288469, -0.20356498],
       [-0.48358651, -0.84805105, -0.53763141],
       [-0.70185658,  0.3308424 ,  1.52198524]])

In [136]:
np.random.randint(0,10, 8) #0-10 is the range and 8 is the number of numbers/values to have

array([0, 7, 9, 8, 9, 6, 4, 3])

In [ ]:
np.random.random_sample